### ISSUE TITLE
Think through our schema

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/pdc#2]
Similar to #1 this issue is intended as a place to discuss and explore our schema; after a little bit of iteration here we'll want to actually document the schema in the form of a PR, and then of course eventually through migrations.

**Comment by slifty** [comment]
```mermaid
erDiagram
  Test {
    int foo
  }
  Another {
    string bar
  }

  Test ||--o{ Another : blorp
```

**Comment by slifty** [comment]
Yes! This is spot on.

As I mentioned on Zulip I'll now take a stab at moving this from a class diagram to an ERD (and think through the fields).

**Comment by bickelj** [comment]
Looking at it again, I guess OrganizationSpecificFields would have been better named OrganizationProposalFields (or the Proposal being somewhere in there). But it's neither here nor there.

**Comment by slifty** [comment]
```mermaid
erDiagram
  CanonicalField {
    int id
    string label
    string type
    datetime dateCreated
  }
  Applicant {
    int id
    string externalId 
    bool hasGivenPermission
  }
  Proposal {
    int id
    int applicantId
    int opportunityId
    datetime dateCreated
  }
  Opportunity {
    int id
    string title
    datetime dateCreated
  }
  ApplicationSchema {
    int id
    int opportunityId
    int version
    datetime dateCreated
  }
  ApplicationSchemaField {
    int id
    int applicationSchemaId
    int canonicalFieldId
    int order
    string label
    datetime dateCreated
  }
  ProposalVersion {
    int id
    int proposalId
    int version
    datetime dateCreated
  }
  ProposalFieldValue {
    int id
    int proposalVersionId
    int proposalSchemaId
    int index
    string value
    datetime dateCreated
  }
  ApplicantFieldValue {
    int id
    int canonicalFieldId
    int sequence
    string value
    datetime dateCreated
  }
  ActivityLog {
    int id
    string actionType
    string log
    datetime dateCreated
  }
  
  Applicant ||--o{ Proposal : submits
  Proposal }|--|| Opportunity : "responds to"
  Opportunity ||--|{ ApplicationSchema : establishes
  ApplicationSchema ||--|{ ApplicationSchemaField : has
  ApplicationSchemaField }o--|| CanonicalField : represents
  Proposal ||--|{ ProposalVersion : has
  ProposalVersion ||--|{ ProposalFieldValue : contains
  ProposalFieldValue }o--|| ApplicationSchemaField : populates
  Applicant ||--|{ ApplicantFieldValue : has
  ApplicantFieldValue }o--|| CanonicalField : "is a default for"
```

The narrative around this schema:

1. An `Applicant` submits a `Proposal`
2. A `Proposal` is a response responses to an `Opportunty`.  An opportunty represents a given challenge, RFP, etc.
3. An `Opportunity` establishes an `Application Schema`. An application schema is the set of fields that make up an application.  An `Opportunity` might update its `Application Schema` over time, which is why an `Opportunity` can have many `Application Schemas`.
4. An `Application Schema` will define many `Application Schema Fields`.
5. An `Application Schema Field` represents a `Canonical Field`.

Meanwhile...

6. A `Proposal` can have more than one `Proposal Version`.  This occurs as a proposal is updated or revised.
7. A `Proposal Version` contains a set of `Proposal Field Values`.  These are the responses that were provided by the `Applicant`.
8. A `Proposal Field Value` contains a response to a given `Application Schema Field`.  Some fields might allow multiple responses, which is why we provide an `index`.

Finally...

9. An `Applicant` has a set of `Applicant Field Values`.  This value can be updated over time based on the `Proposal Field Values` submitted by the applicant.
10. An `Applicant Field Value` represents the "default" response for a `Canonical Field`.

**Comment by slifty** [comment]
There are some use cases that are not yet explicitly captured in the above schema design, but the space is there for them.  I would like to first discuss the use cases before including them.  Specifically:

1. Applicant administrators / who is allowed to opt in or out of PDC
2. Tracking metadata about grant making organizations -- e.g. creating an entity that "owns" the opportunities.

**Comment by slifty** [comment]
We're going to take out `ApplicantFieldValue` and KEEP `ExternalFieldValue`

The thinking is that `ApplicantFieldValue` was serving as a cache of the "right" `ProposalFieldValue` but that is not necessarily needed for our first version and may never be needed.

This would mean that to get the pre-populated value for a given `CanonicalField` we would follow logic such as:

1. Get the latest `ProposalFieldValue` for this `CanonicalField` + `Applicant` pair.
2. If none exists, get the latest `ExternalFieldValue` for this `CanonicalField` + `Applicant` pair.
3. If THAT does not exist, there is no default value.

**Comment by slifty** [comment]
We were considering having "Outcome" just be a field of `Proposal` rather than a separate table.

Having it as a table would allow multiple outcomes over time for a given proposal (e.g. "Semifinalist -> Finalist -> Accepted") with a render-able history.  This seems probably useful!

**Comment by slifty** [comment]
From @jim-mcgowan:

`Funders` will create `Grants`. `Applicants` will complete `Applications` to be considered for `Grants`.

I'll be updating the ERD to reflect this; one followup question I have is whether a "Grant" is referring to the awarded result or the opportunity for an award (e.g. should we call it `Grant` or `GrantOpportunity`) <-- I'm assuming `Grant` for now but it's easy to swap around.

**Comment by slifty** [comment]
Another update: we're sticking with Opportunity for now.

This is also at the point where we can open a PR and move further iteration into future PRs.

**Comment by jmergy** [comment]
Some funders stay away from the term grant and use award, etc. but there are so many different considerations here and so many have different terminology here, it's tough.
